### ISSUE TITLE
not working `&` inside the links

### ISSUE THREAD

**Issue by AptaLinny** [aarroyoc/nodejs-shorteners#2]
i have a discord.js generator bot and then i use:
`http://mypage.com/gen?email=email&password=password` only email is inside the link
Using adf.ly

**Comment by aarroyoc** [comment]
Yes, you're right. I'll fix it as soon as possible

**Comment by AptaLinny** [comment]
It works if you use %26 instead of &

**Comment by aarroyoc** [comment]
Fixed, update to 1.2 in npm. Thanks for reporting!
